package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.testng.annotations.Test;


public class DeleteContactTests extends TestBase {
  @Test
  public void testDeleteContact () {
    app.selectedContact();
    app.deleteSelectedContact();
    app.confirmDeleteContact();
  }

}
