package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;


public class DeleteContactTests extends TestBase {
  @Test
  public void testDeleteContact () {
    app.getContactHelper().selectedContact();
    app.getContactHelper().deleteSelectedContact();
    app.getContactHelper().confirmDeleteContact();
  }

}
